name = "hono-oidc-sample"
main = "./src/index.ts"
compatibility_date = "2024-08-15"

[vars]
BASE_URL = "https://hono-oidc-sample.saigusa758cloudy.workers.dev"

[env.local]
vars = { BASE_URL = "http://localhost:8787" }
